variables:
  MAINT_BRANCH_PATTERN: /^(([0-9]+)\.)?([0-9]+)\.x/
  PREREL_BRANCH_PATTERN: /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/

stages:
  - test
  - release
  - build
  - deploy

unit_test:
  image: public.ecr.aws/docker/library/python:3.11-slim-bookworm
  stage: test
  script:
    - export PYTHONPATH=$CI_PROJECT_DIR
    - pip install -r requirements.txt
    - pip install pytest
    - pytest --junitxml=results.xml
  artifacts:
    paths:
      - results.xml
    reports:
      junit:
        - results.xml


release:
  image: public.ecr.aws/crossref/cicada:latest
  stage: release
  tags:
    - aws
    - ec2
    - amd64
  script:
    - npx semantic-release
  only:
    refs:
      - main
      - alpha
      - $MAINT_BRANCH_PATTERN
      - $PREREL_BRANCH_PATTERN
  artifacts:
    paths:
      - VERSION.txt

build_amd64_image:
  image: public.ecr.aws/crossref/cicada:latest
  stage: build
  tags:
    - aws
    - ec2
    - amd64
  services:
    - docker:dind
  script:
    - echo "version = $(cat VERSION.txt)" > version.py
    - build_image.sh amd64 "${CI_PROJECT_DIR}/Dockerfile.prod" search $CI_COMMIT_TAG $CI_PROJECT_DIR
  only:
    - tags
  artifacts:
    paths:
      - VERSION.txt

build_arm64_image:
  image: public.ecr.aws/crossref/cicada:latest
  stage: build
  tags:
    - aws
    - ec2
    - arm64
  services:
    - docker:dind
  script:
    - echo "version = $(cat VERSION.txt)" > version.py
    - build_image.sh arm64 "${CI_PROJECT_DIR}/Dockerfile.prod" search $CI_COMMIT_TAG $CI_PROJECT_DIR
  only:
    - tags
  artifacts:
    paths:
      - VERSION.txt

multi_arch_manifest:
  image: public.ecr.aws/crossref/cicada:latest
  stage: build
  tags:
    - aws
    - ec2
    - amd64
  services:
    - docker:dind
  needs: ['build_amd64_image', 'build_arm64_image']
  script:
    - create_manifest.sh search $CI_COMMIT_TAG
  only:
    - tags

deploy_search_staging:
  image: public.ecr.aws/crossref/cicada:latest
  stage: deploy
  tags:
    - aws
    - ec2
    - amd64
  variables:
    AWS_DEFAULT_PROFILE: staging
  script:
    - deploy_container.sh cayenne-staging search-staging $CI_COMMIT_TAG
  only:
    - tags

deploy_search_production:
  image: public.ecr.aws/crossref/cicada:latest
  stage: deploy
  tags:
    - aws
    - ec2
    - amd64
  variables:
    AWS_DEFAULT_PROFILE: production
  script:
    - deploy_container.sh cayenne-production search-production $CI_COMMIT_TAG
  only:
    - tags
  when: manual
