FROM public.ecr.aws/docker/library/python:3.11-slim-bookworm

WORKDIR /app

COPY requirements.txt /app
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . /app

CMD [ "gunicorn", "--bind", "0.0.0.0:8000", "--workers=10", "--max-requests=1000", "--max-requests-jitter=20", "--keep-alive=75", "app:app" ]
