FROM public.ecr.aws/docker/library/python:3.11-slim-bookworm

WORKDIR /app

COPY requirements.txt /app
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . /app

CMD [ "gunicorn", "--bind", "0.0.0.0:8000", "--workers=30", "app:app" ]
